Ui signup changes
Carebase-Solutions/carebase-android pull request #39
Opened 2020-09-30 15:32 UTC by tykosc

Changed color of signup buttons to primary color 
Changed outline of textfields to match the sign in screen
greyed out the submit button for invitation code until text is typed
Changed style of email and live demo buttons to outlined buttons for less emphasis.

2020-10-02 04:21 UTC, sak6lab requested changes
Good work! Made it look so good! A couple small things and we should be good. 🙌

2020-10-02 04:21 UTC, sak6lab commented on app/src/main/res/layout/activity_signup.xml
>              style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
Change this to the style "Widget.Carebase.TextInputLayout" in style.xml similar to how it was done in the login screen. This so if we ever decide to change the overall style we can change it from there.

2020-10-02 04:21 UTC, sak6lab commented on app/src/main/res/layout/activity_signup.xml
>          <com.google.android.material.textfield.TextInputLayout
Change the Invitation code text field so that it does not always default to all caps when entering on android keyboard.

2020-10-02 04:31 UTC, sak6lab commented on app/src/main/res/layout/activity_signup.xml
>              style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
Also change the inputType of the invitation code text field to the regular configuration rather than the AllCaps setting.

2020-10-07 15:02 UTC, tykosc commented
Made the requested changes!

2020-10-07 16:52 UTC, sak6lab approved these changes
Good Work! 👍

2020-10-07 16:52 UTC, merged