Fixing udis with + in front (issue #50)
Carebase-Solutions/carebase-android pull request #55
Opened 2020-11-05 19:56 UTC by tykosc

**New behavior**
When a primary HIBCC barcode is entered as a udi, di level information is retrieved from the GUIDID database.  This is done by sending the primary barcode as a di with the first character (+) and last character removed. 

The user must then manually enter missing information (location, lot number, expiration date).

When saving to the database, the udi will be saved in the format: udi + $$ + expiration date MMYY + lot number.  

**To Test**
Enter a primary HIBCC barcode (one that starts with +), autopopulate, and save.  Attempt to save the same barcode twice with different expiration dates and make sure it saves twice with a unique udi. 

**NOTE:** the barcode +H965457561K will still crash the app due to issue #54

2020-11-11 02:19 UTC, sak6lab requested changes

2020-11-11 02:19 UTC, sak6lab commented on app/src/main/java/org/getcarebase/carebase/activities/Main/fragments/ItemDetailFragment.java
> +        //save the udi to include expiration date and lot number
Check if the user entering a HIBCC di before doing this. This unintentionally appends the $$mmyylotnum string to to GS1 udis.

2020-11-11 04:54 UTC, tykosc commented on app/src/main/java/org/getcarebase/carebase/activities/Main/fragments/ItemDetailFragment.java
> +        //save the udi to include expiration date and lot number
done

2020-11-11 21:02 UTC, sak6lab requested changes
So I tested with the barcode +H9651058006 and I found that if we were to scan the same device ( a device with the same expiration date and lot number) again instead of adding to the quantity that was already in the database it replaces the entry. We can see when we autopopulate the quantity is zero which is fine since we did not enter the expiration date and lot number to match the device. When the user saves the item is should check if there is a current quantity and calculate the new quantity if `isDi` is true in `saveData()`.

2020-11-11 21:08 UTC, sak6lab commented
This is kind of a work around cause really we should update the quantity as we enter the expiration date and the lot number but that would require a lot of unnecessary database hits.

2020-11-13 01:09 UTC, sak6lab approved these changes
I tested a new HIBCC barcode and added the same barcode again. I also tested a GS1 barcode in the GUDID and everything seemed to work

2020-11-13 01:09 UTC, sak6lab commented on app/src/main/java/org/getcarebase/carebase/activities/Main/fragments/ItemDetailFragment.java
> +    public void saveToDB(String name_str, String type_str, String company_str, String di_str, String site_name_str,
Good work extracting the method! Definitely the async call made it difficult. It now works as expected however there is too many parameters in the `saveToDB()` method and when we refactor this activity hopefully we can handle this case better. This is not clean code, but it is hard to make it cleaner without revamping how saving is done. When we are refactoring this page this case should be handled cleaner.

2020-11-14 17:05 UTC, merged