Issue 74 molly
Carebase-Solutions/carebase-android pull request #84
Opened 2021-02-03 20:28 UTC by molly34762

- Added labels next to mini floating action buttons
- changes background tint of add button upon clicking

2021-02-04 00:07 UTC, sak6lab requested changes
The labels are not that apparent as there is no background for the labels. Also change title of this PR to something more descriptive like 

> Added labels to mini floating action buttons

Other than that you should be good

2021-02-04 00:07 UTC, sak6lab commented on app/src/main/res/layout/mini_manual_add_device_fab.xml
> +    android:orientation="vertical">
Change this to `horizontal`

2021-02-04 00:07 UTC, sak6lab commented on app/src/main/res/layout/mini_manual_add_device_fab.xml
> +        android:id="@+id/manual_add_device_fab_label"
- Add 4dp padding and 4dp horizontal padding
- Add rounded corners by setting a white rounded corner background
- Add elevation of 6dp to match floating action buttons

2021-02-05 14:28 UTC, molly34762 commented
@sak6lab I made some changes to the UI, can you take a quick look to confirm? Thanks!

2021-02-05 14:39 UTC, molly34762 commented
@sak6lab I have changed the ui of the labels, however I am not sure why the onclick for the scanning and adding device button doesn't work.

2021-02-06 17:36 UTC, sak6lab commented
<img width="145" alt="Screen Shot 2021-02-06 at 12 33 23 PM" src="https://user-images.githubusercontent.com/15002610/107125360-85caf600-6877-11eb-8411-f4bf38c1d6f7.png">

- gave labels uniform width to make it uniform
- cleaned up animations
- made actual mini button unclickable to avoid the issue where mini buttons where clickable and would not perform correctly

2021-02-06 18:20 UTC, sak6lab approved these changes

2021-02-06 18:21 UTC, merged